version: '3.7'

configs:
  api_server_config:
    file: ./nginx.conf

volumes:
  api_staticfiles:

services:
  api_db:
    image: postgres:11.2-alpine
    env_file:
      - ../.env
    ports:
      - 5400:5432
  
  api_app:
    image: registry.gitlab.com/ahmadsyafiq93/blog-api:latest
    command: /start
    env_file:
      - ../.env
    depends_on:
      - api_db
    ports:
      - 8000:8000
    volumes:
      - api_staticfiles:/app/staticfiles

  api_server:
    image: nginx:1.15.8-alpine
    ports:
      - 80:80
    configs:
      - source: api_server_config
        target: /etc/nginx/nginx.conf
    volumes:
      - api_staticfiles:/staticfiles:ro
    depends_on:
      - api_app